# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

---
driver:
  name: default
dependency:
  name: galaxy
  options:
    requirements-file: molecule/kubevirt/collections.yml
provisioner:
  name: ansible
  playbooks:
    create: ../shared/kubevirt-create.yml
    destroy: ../shared/kubevirt-destroy.yml
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false
  log: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
platforms:
#  # K8s needs to authenticate to registry.redhat.io to pull this image
#  - name: molecule-ostest-rhel9
#    image: registry.redhat.io/rhel9/rhel-guest-image
#    namespace: molecule
#    ssh_service:
#      type: NodePort
#    ansible_user: cloud-user
#    memory: 1Gi
  - name: molecule-ostest-centos9
    image: ghcr.io/clifford2/kubevirt-containerdisk:centos-stream9.v20251223.0
    namespace: molecule
    ssh_service:
      type: NodePort
    ansible_user: molecule
    memory: 1Gi
  - name: molecule-ostest-centos10
    image: ghcr.io/clifford2/kubevirt-containerdisk:centos-stream10.v20251223.1
    namespace: molecule
    ssh_service:
      type: NodePort
    ansible_user: molecule
    memory: 1Gi
  - name: molecule-ostest-debian12
    image: ghcr.io/clifford2/kubevirt-containerdisk:debian12.v20251112-2294
    namespace: molecule
    ssh_service:
      type: NodePort
    ansible_user: molecule
    memory: 1Gi
  - name: molecule-ostest-debian13
    image: ghcr.io/clifford2/kubevirt-containerdisk:debian13.v20251117-2299
    namespace: molecule
    ssh_service:
      type: NodePort
    ansible_user: molecule
    memory: 1Gi
  - name: molecule-ostest-opensuse15
    image: ghcr.io/clifford2/kubevirt-containerdisk:opensuse-15.6.v1.0.2-1.99
    namespace: molecule
    ssh_service:
      type: NodePort
    ansible_user: molecule
    memory: 1Gi
  - name: molecule-ostest-ubuntu24
    image: ghcr.io/clifford2/kubevirt-containerdisk:ubuntu2404.v20251213
    namespace: molecule
    ssh_service:
      type: NodePort
    ansible_user: molecule
    memory: 1Gi
