# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

ARG BUILD_TIME
ARG GIT_REVISION

FROM scratch

# Get latest image from https://cloud.centos.org/centos/10-stream/x86_64/images/
ARG VERSION=20251223.1
ADD --chown=107:107 --chmod=0644 https://cloud.centos.org/centos/10-stream/x86_64/images/CentOS-Stream-GenericCloud-x86_64-10-$(VERSION}.x86_64.qcow2 /disk/

LABEL maintainer="Clifford Weinmann <https://www.cliffordweinmann.com/>"
LABEL org.opencontainers.image.authors="Clifford Weinmann <https://www.cliffordweinmann.com/>"
LABEL org.opencontainers.image.created="${BUILD_TIME}"
LABEL org.opencontainers.image.description="Ansible Molecule KubeVirt containerDisk Image for CentOS Stream 10"
LABEL org.opencontainers.image.licenses="MIT-0"
LABEL org.opencontainers.image.revision="${GIT_REVISION}"
LABEL org.opencontainers.image.source="https://github.com/clifford2/molecule-containers"
LABEL org.opencontainers.image.title="kubevirt-containerdisk:centos-stream10"
LABEL org.opencontainers.image.url="https://github.com/clifford2/molecule-containers"
LABEL org.opencontainers.image.version="${VERSION}"
