# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

ARG VERSION=20250327
FROM scratch
LABEL maintainer="Clifford Weinmann <https://www.cliffordweinmann.com/>"
LABEL org.opencontainers.image.source https://github.com/clifford2/molecule-containers
ADD --chown=107:107 --chmod=0644 https://cloud-images.ubuntu.com/noble/20250327/noble-server-cloudimg-amd64.img /disk/
