# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

---
- name: "Retrieve container log"
  ansible.builtin.command:
    cmd: >-
      {% raw %}
      docker logs
      {% endraw %}
      {{ item.invocation.module_args.name }}
  changed_when: false
  failed_when: false
  register: molecule_logfile_cmd

- name: "Display container log"
  ansible.builtin.fail:
    msg: "{{ molecule_logfile_cmd.stderr | default('No logs', true) }}"
