# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

---
apiVersion: v1
kind: Namespace
metadata:
  name: molecule
  labels:
    kubernetes.io/metadata.name: molecule
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: molecule
  namespace: molecule
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: molecule
  name: molecule
rules:
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "edit"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "edit"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: molecule
  namespace: molecule
subjects:
  - kind: ServiceAccount
    name: molecule
    namespace: molecule
roleRef:
  kind: Role
  name: molecule
  apiGroup: rbac.authorization.k8s.io
