# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

---
- name: 'Converge'
  hosts: all
  gather_facts: false
  tasks:

    - name: 'Collect required facts'
      ansible.builtin.setup:
        gather_subset:
          - os_family
          - distribution

    - name: 'Show some facts about our container'
      ansible.builtin.debug:
        msg: "Running on: architecture {{ ansible_facts['architecture'] }} - os_family {{ ansible_facts['os_family'] | lower }} - distribution {{ ansible_facts['distribution'] | lower }} version {{ ansible_facts['distribution_major_version'] }}"
