# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

---
driver:
  name: default
  options:
    managed: false
    login_cmd_template: "podman exec -ti {instance} bash"
    ansible_connection_options:
      ansible_connection: containers.podman.podman
dependency:
  name: galaxy
  options:
    requirements-file: molecule/podman/collections.yml
provisioner:
  name: ansible
  playbooks:
    create: ../shared/podman-create.yml
    converge: converge.yml
    destroy: ../shared/podman-destroy.yml
platforms:
  # Red Hat Universal Base Image 8
  - name: molecule-example-ubi8
    image: registry.access.redhat.com/ubi8/ubi-init:8.10-1756225952
    command: /sbin/init
  # Red Hat Universal Base Image 9
  - name: molecule-example-ubi9
    image: registry.access.redhat.com/ubi9/ubi-init:9.6-1756999027
    command: /sbin/init
  # Red Hat Universal Base Image 10
  - name: molecule-example-ubi10
    image: registry.access.redhat.com/ubi10/ubi-init:10.0-1755764354
    command: /sbin/init
  # CentOS Stream 8
  - name: molecule-example-centos8
    image: ghcr.io/clifford2/molecule-platform:centos-stream8.v1.0.0
    command: /sbin/init
  # CentOS Stream 9
  - name: molecule-example-centos9
    image: ghcr.io/clifford2/molecule-platform:centos-stream9.v1.0.1-20251224
    command: /sbin/init
  # CentOS Stream 10
  - name: molecule-example-centos10
    image: quay.io/centos/centos:stream10
    command: /sbin/init
  # Debian 12 (Bookworm)
  - name: molecule-example-debian12
    image: ghcr.io/clifford2/molecule-platform:debian12.v1.0.5
    command: /sbin/init
  # Debian 13 (Trixie)
  - name: molecule-example-debian13
    image: ghcr.io/clifford2/molecule-platform:debian13.v1.0.1
    command: /sbin/init
  # Fedora 40
  - name: molecule-example-fedora40
    image: ghcr.io/clifford2/molecule-platform:fedora40.v1.0.0-20260102
    command: /sbin/init
  # Fedora 41
  - name: molecule-example-fedora41
    image: ghcr.io/clifford2/molecule-platform:fedora41.v1.0.0-20260102
    command: /sbin/init
  # Fedora 42
  - name: molecule-example-fedora42
    image: ghcr.io/clifford2/molecule-platform:fedora42.v1.0.2-20260102
    command: /sbin/init
  # Fedora 43
  - name: molecule-example-fedora43
    image: ghcr.io/clifford2/molecule-platform:fedora43.v1.0.0-20260102
    command: /sbin/init
  # SLES 15
  - name: molecule-example-sle15
    image: ghcr.io/clifford2/molecule-platform:sle15.v1.0.5
    command: /sbin/init
  # SLES 16
  - name: molecule-example-sle16
    image: ghcr.io/clifford2/molecule-platform:sle16.v1.0.0
    command: /sbin/init
  # Ubuntu 22.04 LTS
  - name: molecule-example-ubuntu2204
    image: ghcr.io/clifford2/molecule-platform:ubuntu2204.v1.0.3
    command: /sbin/init
  # Ubuntu 24.04 LTS
  - name: molecule-example-ubuntu2404
    image: ghcr.io/clifford2/molecule-platform:ubuntu2404.v1.0.3
    command: /sbin/init
