# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

# Based on UBI 9 Dockerfile

ARG BUILD_TIME
ARG GIT_REVISION
ARG VERSION=1.0.0

# Base image is not immutable, but last update was 2024-05-28T21:46:33.187272482Z
FROM quay.io/centos/centos:stream8

RUN  echo 'Fix repos' \
	&& sed -i 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*.repo \
	&& sed -i 's|#baseurl=http://mirror.centos.org|baseurl=https://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo

RUN dnf -y install systemd procps-ng python3.12 python3-dnf && dnf clean all

#mask systemd-machine-id-commit.service - partial fix for https://bugzilla.redhat.com/show_bug.cgi?id=1472439
RUN systemctl mask systemd-remount-fs.service dev-hugepages.mount sys-fs-fuse-connections.mount systemd-logind.service getty.target console-getty.service systemd-udev-trigger.service systemd-udevd.service systemd-random-seed.service systemd-machine-id-commit.service

CMD ["/sbin/init"]

STOPSIGNAL SIGRTMIN+3

LABEL maintainer="Clifford Weinmann <https://www.cliffordweinmann.com/>"
LABEL org.opencontainers.image.authors="Clifford Weinmann <https://www.cliffordweinmann.com/>"
LABEL org.opencontainers.image.created="${BUILD_TIME}"
LABEL org.opencontainers.image.description="Ansible Molecule Container Image for CentOS Stream 8"
LABEL org.opencontainers.image.licenses="MIT-0"
LABEL org.opencontainers.image.revision="${GIT_REVISION}"
LABEL org.opencontainers.image.source="https://github.com/clifford2/molecule-containers"
LABEL org.opencontainers.image.title="molecule-platform:centos-stream8"
LABEL org.opencontainers.image.url="https://github.com/clifford2/molecule-containers"
LABEL org.opencontainers.image.version="${VERSION}"
