# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

ARG VERSION=1.0.1

FROM registry.suse.com/bci/bci-init:15.6.30.11

RUN zypper install -y python311 python311-rpm procps && zypper clean -a
