# SPDX-FileCopyrightText: © 2026 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

ARG VERSION=1.0.0

FROM registry.suse.com/bci/bci-init:16.0-8.10

LABEL maintainer="Clifford Weinmann <https://www.cliffordweinmann.com/>"
LABEL org.opencontainers.image.source="https://github.com/clifford2/molecule-containers"

RUN zypper install -y python313 python313-rpm procps && zypper clean -a
