# SPDX-FileCopyrightText: © 2026 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

ARG BUILD_TIME
ARG GIT_REVISION
ARG VERSION=1.0.1

# Find latest image tag at https://registry.suse.com/repositories?categories%5B%5D=bci
FROM registry.suse.com/bci/bci-init:16.0-10.1

RUN zypper install -y python313 python313-rpm procps && zypper clean -a

LABEL maintainer="Clifford Weinmann <https://www.cliffordweinmann.com/>"
LABEL org.opencontainers.image.authors="Clifford Weinmann <https://www.cliffordweinmann.com/>"
LABEL org.opencontainers.image.created="${BUILD_TIME}"
LABEL org.opencontainers.image.description="Ansible Molecule Container Image for SLE 16 BCI"
LABEL org.opencontainers.image.licenses="MIT-0"
LABEL org.opencontainers.image.revision="${GIT_REVISION}"
LABEL org.opencontainers.image.source="https://github.com/clifford2/molecule-containers"
LABEL org.opencontainers.image.title="molecule-platform:sle16"
LABEL org.opencontainers.image.url="https://github.com/clifford2/molecule-containers"
LABEL org.opencontainers.image.version="${VERSION}"
