# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: BSD-2-Clause

ARG VERSION=1.0.0
FROM registry.suse.com/bci/bci-init:15.6.30.6
RUN zypper install -y python311 python311-rpm procps && zypper clean -a
