# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
#
# SPDX-License-Identifier: MIT-0

---
- name: "Verify"
  hosts: all
  gather_facts: false
  tasks:

    - name: "Check if /etc/os-release exists"
      ansible.builtin.stat:
        path: "/etc/os-release"
        get_checksum: false
        follow: false
      register: molecule_verify_stat

    - name: "Ensure that /etc/os-release exists"
      ansible.builtin.assert:
        that:
          - molecule_verify_stat.stat.exists
        fail_msg: "Oops, looks like our converge step didn't achieve it's goals"
        success_msg: "Well done, it worked!"
