# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
# SPDX-License-Identifier: MIT-0

name: Create and publish a container images

on:
  push:
    # Configures this workflow to run every time a change is pushed to the branch called `main`.
    branches: ['main']
    # Pattern matched against refs/tags - see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags
    # tags:        
    #   - '*'  # Push events to every tag not containing /

env:
  REGISTRY: ghcr.io

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-24.04
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        run: podman login ghrc.io --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}"

      - name: Build & push container images
        run: |
          make build-container
          make push-container

      # - name: Build & push kubevirt VM images
      #   run: |
      #     make build-vm
      #     make push-vm
