---
# SPDX-FileCopyrightText: © 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>
# SPDX-License-Identifier: MIT-0

name: "Debian 13 container image"

"on":
  workflow_dispatch:
  push:
    # Configures this workflow to run every time a change is pushed to the branch called `main`.
    branches: ['main']
    # Pattern matched specific path
    paths:
      - "podman/Containerfile.debian13"
      - ".github/workflows/build-podman-debian13.yml"

jobs:

  build-container-images:
    runs-on: "ubuntu-24.04"
    permissions:
      contents: "read"
      packages: "write"
      attestations: "write"
      id-token: "write"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"

      # Set up QEMU for ARM64 emulation
      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@v4"

      # Set up Docker Buildx (Creates the correct builder driver)
      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@v4"

      - name: "Log in to the Container registry"
        run: docker login ghcr.io --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}"

      - name: "Build & push container images"
        run: |
          make build-multiarch-container CTPLATFORMS=debian13
